# Generated by Django 2.1.3 on 2018-11-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181128_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='score',
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
