# Generated by Django 2.1.3 on 2018-11-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181128_1936'),
        ('posts', '0003_comment'),
    ]

    operations = [
    ]
