# Generated by Django 2.1.3 on 2018-11-29 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_merge_20181128_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='score',
        ),
        migrations.AlterField(
            model_name='post',
            name='user_has_voted',
            field=models.ManyToManyField(related_name='user_vote', through='posts.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post'),
        ),
    ]
