# Generated by Django 2.1.3 on 2018-11-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181129_1202'),
        ('posts', '0004_auto_20181130_1653'),
    ]

    operations = [
    ]
